### ISSUE TITLE
Mi mirada del proyecto

### ISSUE THREAD

**Issue by yaninagm** [lightning-round/doc#1]
Plataforma educativa que permita unir lo mejor de todos los cursos en un solo lugar, utilizando como método de evaluación el juego, y la cooperación, premiando con puntos a aquellas personas que logren alcanzar objetivos y puedan transmitir sus ideas a los otros usuarios. Estos puntos en un futuro podrán canjearse por premios reales que se obtendrán a partir de empresas que brinden sus productos con el fin de hacerse conocer.

Los cursos se pueden clasificar por distintas características, mas recomendados, mas tomados, por dificultad, etc...

La plataforma debe permitir a las personas poder crear sus curso, y se le podría brindar la posibilidad de que arme un curso a partir de otros ya existentes o que los mejore

**Comment by navicor90** [comment]
Me parece interesante que los cursos tengan una seccion de desafíos, los que podrían ser evaluados por los administradores del curso. En esta seccion de desafíos te deberías  poder inscribir al desafío y allí te daría acceso a la informacion del mismo, pensba anoche que el metodo de evaluacion puede pasar por los administradores y que en la información por ejemplo diga *hacer un pull request al siguiente repo y que te lo acepten * inicialmente la validación no haría falta que pase por nosotros sinó por el administrador.
 Además pensé que existiran multiples __disciplinas o asignaturas__ generales creadas por el administrador de la app como  para que no se vuelva tan caotico, y un curso(que pertenecerá a alguna disciplina) puede hacer como una *solicitud de desafio interdisiplinario*  esto es para que se pueda acceder a ver el desafío desde otras disciplinas... Eso es especialmente para promover trabajo en equipo entre disciplinas. Podríamos crear el rol de Heroe del desafío (No lider por una cuestión de que no es un lindo nombre) en el que te encargas de ser el lider, pero renuncias a cierta ventaja en puntos, donde los usuarios no Heroes recibiran mayor puntaje
 Otra de las ventajas que le vi al hecho de las disciplinas, es que podía tener un menú principal como de status, donde te mostrara tus __capacidades/habilidades__ en las distintas disciplinas. 
Obviamente tus habilidades pueden destrabarte otros cursos o desafíos .

**Comment by adamantike** [comment]
Obsoleto por cambio de proyecto.
